# Generated by Django 5.1.5 on 2025-02-10 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_options_alter_cart_book_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
    ]
