# Generated by Django 5.1.5 on 2025-02-10 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_id'),
        ('cart', '0004_alter_cart_id'),
        ('customer', '0004_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_cart', to='book.book'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_cart', to='customer.customer'),
        ),
    ]
